services:
  - name: web
    buildCommand: python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi --bind 0.0.0.0:$PORT --workers 4
    healthCheckPath: /
    env:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        value: your_secret_key
